import Modal from "@/components/modal";
import PayoutModal, { usePayoutModal } from "@/components/payout-modal";
import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [show, setShow] = useState(true);
  const payoutModal = usePayoutModal();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <base href="/" />
      </Head>
      <main className={styles.main}>
        <PayoutModal controller={payoutModal} />
      </main>
    </>
  );
}
